// Code generated by mockery. DO NOT EDIT.

package mockusecaseslot

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function with given fields: ctx, slots
func (_m *MockRepository) BulkUpsert(ctx context.Context, slots []domain.Slot) error {
	ret := _m.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Slot) error); ok {
		r0 = rf(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type MockRepository_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - ctx context.Context
//   - slots []domain.Slot
func (_e *MockRepository_Expecter) BulkUpsert(ctx interface{}, slots interface{}) *MockRepository_BulkUpsert_Call {
	return &MockRepository_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", ctx, slots)}
}

func (_c *MockRepository_BulkUpsert_Call) Run(run func(ctx context.Context, slots []domain.Slot)) *MockRepository_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Slot))
	})
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) Return(_a0 error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) RunAndReturn(run func(context.Context, []domain.Slot) error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// CountByRoomAndDate provides a mock function with given fields: ctx, roomID, from, to
func (_m *MockRepository) CountByRoomAndDate(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time) (int, error) {
	ret := _m.Called(ctx, roomID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountByRoomAndDate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (int, error)); ok {
		return rf(ctx, roomID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) int); ok {
		r0 = rf(ctx, roomID, from, to)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, roomID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountByRoomAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByRoomAndDate'
type MockRepository_CountByRoomAndDate_Call struct {
	*mock.Call
}

// CountByRoomAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) CountByRoomAndDate(ctx interface{}, roomID interface{}, from interface{}, to interface{}) *MockRepository_CountByRoomAndDate_Call {
	return &MockRepository_CountByRoomAndDate_Call{Call: _e.mock.On("CountByRoomAndDate", ctx, roomID, from, to)}
}

func (_c *MockRepository_CountByRoomAndDate_Call) Run(run func(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time)) *MockRepository_CountByRoomAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CountByRoomAndDate_Call) Return(_a0 int, _a1 error) *MockRepository_CountByRoomAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountByRoomAndDate_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) (int, error)) *MockRepository_CountByRoomAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailable provides a mock function with given fields: ctx, roomID, from, to
func (_m *MockRepository) ListAvailable(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time) ([]domain.Slot, error) {
	ret := _m.Called(ctx, roomID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.Slot, error)); ok {
		return rf(ctx, roomID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []domain.Slot); ok {
		r0 = rf(ctx, roomID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, roomID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type MockRepository_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ListAvailable(ctx interface{}, roomID interface{}, from interface{}, to interface{}) *MockRepository_ListAvailable_Call {
	return &MockRepository_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, roomID, from, to)}
}

func (_c *MockRepository_ListAvailable_Call) Run(run func(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time)) *MockRepository_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListAvailable_Call) Return(_a0 []domain.Slot, _a1 error) *MockRepository_ListAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAvailable_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.Slot, error)) *MockRepository_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
