// Code generated by mockery. DO NOT EDIT.

package mockusecaseslot

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// GetByRoomID provides a mock function with given fields: ctx, roomID
func (_m *MockScheduleRepository) GetByRoomID(ctx context.Context, roomID uuid.UUID) (*domain.Schedule, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoomID")
	}

	var r0 *domain.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Schedule, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Schedule); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRoomID'
type MockScheduleRepository_GetByRoomID_Call struct {
	*mock.Call
}

// GetByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockScheduleRepository_Expecter) GetByRoomID(ctx interface{}, roomID interface{}) *MockScheduleRepository_GetByRoomID_Call {
	return &MockScheduleRepository_GetByRoomID_Call{Call: _e.mock.On("GetByRoomID", ctx, roomID)}
}

func (_c *MockScheduleRepository_GetByRoomID_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockScheduleRepository_GetByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockScheduleRepository_GetByRoomID_Call) Return(_a0 *domain.Schedule, _a1 error) *MockScheduleRepository_GetByRoomID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetByRoomID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Schedule, error)) *MockScheduleRepository_GetByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
