// Code generated by mockery. DO NOT EDIT.

package mockslothandler

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GetAvailableSlots provides a mock function with given fields: ctx, roomID, date
func (_m *MockUseCase) GetAvailableSlots(ctx context.Context, roomID uuid.UUID, date time.Time) ([]domain.Slot, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 []domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]domain.Slot, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []domain.Slot); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlots'
type MockUseCase_GetAvailableSlots_Call struct {
	*mock.Call
}

// GetAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - date time.Time
func (_e *MockUseCase_Expecter) GetAvailableSlots(ctx interface{}, roomID interface{}, date interface{}) *MockUseCase_GetAvailableSlots_Call {
	return &MockUseCase_GetAvailableSlots_Call{Call: _e.mock.On("GetAvailableSlots", ctx, roomID, date)}
}

func (_c *MockUseCase_GetAvailableSlots_Call) Run(run func(ctx context.Context, roomID uuid.UUID, date time.Time)) *MockUseCase_GetAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockUseCase_GetAvailableSlots_Call) Return(_a0 []domain.Slot, _a1 error) *MockUseCase_GetAvailableSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetAvailableSlots_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]domain.Slot, error)) *MockUseCase_GetAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
