// Code generated by mockery. DO NOT EDIT.

package mockusecaseschedule

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateWithSlots provides a mock function with given fields: ctx, _a1, slots
func (_m *MockRepository) CreateWithSlots(ctx context.Context, _a1 *domain.Schedule, slots []domain.Slot) error {
	ret := _m.Called(ctx, _a1, slots)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithSlots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Schedule, []domain.Slot) error); ok {
		r0 = rf(ctx, _a1, slots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateWithSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithSlots'
type MockRepository_CreateWithSlots_Call struct {
	*mock.Call
}

// CreateWithSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Schedule
//   - slots []domain.Slot
func (_e *MockRepository_Expecter) CreateWithSlots(ctx interface{}, _a1 interface{}, slots interface{}) *MockRepository_CreateWithSlots_Call {
	return &MockRepository_CreateWithSlots_Call{Call: _e.mock.On("CreateWithSlots", ctx, _a1, slots)}
}

func (_c *MockRepository_CreateWithSlots_Call) Run(run func(ctx context.Context, _a1 *domain.Schedule, slots []domain.Slot)) *MockRepository_CreateWithSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Schedule), args[2].([]domain.Slot))
	})
	return _c
}

func (_c *MockRepository_CreateWithSlots_Call) Return(_a0 error) *MockRepository_CreateWithSlots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateWithSlots_Call) RunAndReturn(run func(context.Context, *domain.Schedule, []domain.Slot) error) *MockRepository_CreateWithSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRoomID provides a mock function with given fields: ctx, roomID
func (_m *MockRepository) GetByRoomID(ctx context.Context, roomID uuid.UUID) (*domain.Schedule, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoomID")
	}

	var r0 *domain.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Schedule, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Schedule); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRoomID'
type MockRepository_GetByRoomID_Call struct {
	*mock.Call
}

// GetByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockRepository_Expecter) GetByRoomID(ctx interface{}, roomID interface{}) *MockRepository_GetByRoomID_Call {
	return &MockRepository_GetByRoomID_Call{Call: _e.mock.On("GetByRoomID", ctx, roomID)}
}

func (_c *MockRepository_GetByRoomID_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockRepository_GetByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByRoomID_Call) Return(_a0 *domain.Schedule, _a1 error) *MockRepository_GetByRoomID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByRoomID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Schedule, error)) *MockRepository_GetByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
