// Code generated by mockery. DO NOT EDIT.

package mockroomhandler

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function with given fields: ctx, name, description, capacity
func (_m *MockUseCase) CreateRoom(ctx context.Context, name string, description *string, capacity *int) (*domain.Room, error) {
	ret := _m.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *int) (*domain.Room, error)); ok {
		return rf(ctx, name, description, capacity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *int) *domain.Room); ok {
		r0 = rf(ctx, name, description, capacity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *int) error); ok {
		r1 = rf(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockUseCase_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - capacity *int
func (_e *MockUseCase_Expecter) CreateRoom(ctx interface{}, name interface{}, description interface{}, capacity interface{}) *MockUseCase_CreateRoom_Call {
	return &MockUseCase_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, name, description, capacity)}
}

func (_c *MockUseCase_CreateRoom_Call) Run(run func(ctx context.Context, name string, description *string, capacity *int)) *MockUseCase_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*int))
	})
	return _c
}

func (_c *MockUseCase_CreateRoom_Call) Return(_a0 *domain.Room, _a1 error) *MockUseCase_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CreateRoom_Call) RunAndReturn(run func(context.Context, string, *string, *int) (*domain.Room, error)) *MockUseCase_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListRooms provides a mock function with given fields: ctx
func (_m *MockUseCase) ListRooms(ctx context.Context) ([]domain.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 []domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_ListRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRooms'
type MockUseCase_ListRooms_Call struct {
	*mock.Call
}

// ListRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) ListRooms(ctx interface{}) *MockUseCase_ListRooms_Call {
	return &MockUseCase_ListRooms_Call{Call: _e.mock.On("ListRooms", ctx)}
}

func (_c *MockUseCase_ListRooms_Call) Run(run func(ctx context.Context)) *MockUseCase_ListRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUseCase_ListRooms_Call) Return(_a0 []domain.Room, _a1 error) *MockUseCase_ListRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_ListRooms_Call) RunAndReturn(run func(context.Context) ([]domain.Room, error)) *MockUseCase_ListRooms_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
