// Code generated by mockery. DO NOT EDIT.

package mockbookinghandler

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function with given fields: ctx, userID, bookingID
func (_m *MockUseCase) CancelBooking(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, userID, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockUseCase_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - bookingID uuid.UUID
func (_e *MockUseCase_Expecter) CancelBooking(ctx interface{}, userID interface{}, bookingID interface{}) *MockUseCase_CancelBooking_Call {
	return &MockUseCase_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, userID, bookingID)}
}

func (_c *MockUseCase_CancelBooking_Call) Run(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID)) *MockUseCase_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUseCase_CancelBooking_Call) Return(_a0 *domain.Booking, _a1 error) *MockUseCase_CancelBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CancelBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Booking, error)) *MockUseCase_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function with given fields: ctx, userID, slotID, createConferenceLink
func (_m *MockUseCase) CreateBooking(ctx context.Context, userID uuid.UUID, slotID uuid.UUID, createConferenceLink bool) (*domain.Booking, error) {
	ret := _m.Called(ctx, userID, slotID, createConferenceLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) (*domain.Booking, error)); ok {
		return rf(ctx, userID, slotID, createConferenceLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) *domain.Booking); ok {
		r0 = rf(ctx, userID, slotID, createConferenceLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, userID, slotID, createConferenceLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockUseCase_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - slotID uuid.UUID
//   - createConferenceLink bool
func (_e *MockUseCase_Expecter) CreateBooking(ctx interface{}, userID interface{}, slotID interface{}, createConferenceLink interface{}) *MockUseCase_CreateBooking_Call {
	return &MockUseCase_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, userID, slotID, createConferenceLink)}
}

func (_c *MockUseCase_CreateBooking_Call) Run(run func(ctx context.Context, userID uuid.UUID, slotID uuid.UUID, createConferenceLink bool)) *MockUseCase_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockUseCase_CreateBooking_Call) Return(_a0 *domain.Booking, _a1 error) *MockUseCase_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CreateBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) (*domain.Booking, error)) *MockUseCase_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyBookings provides a mock function with given fields: ctx, userID
func (_m *MockUseCase) GetMyBookings(ctx context.Context, userID uuid.UUID) ([]domain.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyBookings")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetMyBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyBookings'
type MockUseCase_GetMyBookings_Call struct {
	*mock.Call
}

// GetMyBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUseCase_Expecter) GetMyBookings(ctx interface{}, userID interface{}) *MockUseCase_GetMyBookings_Call {
	return &MockUseCase_GetMyBookings_Call{Call: _e.mock.On("GetMyBookings", ctx, userID)}
}

func (_c *MockUseCase_GetMyBookings_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUseCase_GetMyBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUseCase_GetMyBookings_Call) Return(_a0 []domain.Booking, _a1 error) *MockUseCase_GetMyBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetMyBookings_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.Booking, error)) *MockUseCase_GetMyBookings_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookings provides a mock function with given fields: ctx, page, pageSize
func (_m *MockUseCase) ListBookings(ctx context.Context, page int, pageSize int) ([]domain.Booking, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListBookings")
	}

	var r0 []domain.Booking
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Booking, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.Booking); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUseCase_ListBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookings'
type MockUseCase_ListBookings_Call struct {
	*mock.Call
}

// ListBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockUseCase_Expecter) ListBookings(ctx interface{}, page interface{}, pageSize interface{}) *MockUseCase_ListBookings_Call {
	return &MockUseCase_ListBookings_Call{Call: _e.mock.On("ListBookings", ctx, page, pageSize)}
}

func (_c *MockUseCase_ListBookings_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockUseCase_ListBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUseCase_ListBookings_Call) Return(_a0 []domain.Booking, _a1 int, _a2 error) *MockUseCase_ListBookings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUseCase_ListBookings_Call) RunAndReturn(run func(context.Context, int, int) ([]domain.Booking, int, error)) *MockUseCase_ListBookings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
