// Code generated by mockery. DO NOT EDIT.

package mockauthhandler

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// DummyLogin provides a mock function with given fields: ctx, role
func (_m *MockUseCase) DummyLogin(ctx context.Context, role string) (string, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for DummyLogin")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_DummyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DummyLogin'
type MockUseCase_DummyLogin_Call struct {
	*mock.Call
}

// DummyLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *MockUseCase_Expecter) DummyLogin(ctx interface{}, role interface{}) *MockUseCase_DummyLogin_Call {
	return &MockUseCase_DummyLogin_Call{Call: _e.mock.On("DummyLogin", ctx, role)}
}

func (_c *MockUseCase_DummyLogin_Call) Run(run func(ctx context.Context, role string)) *MockUseCase_DummyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUseCase_DummyLogin_Call) Return(_a0 string, _a1 error) *MockUseCase_DummyLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_DummyLogin_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUseCase_DummyLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockUseCase) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUseCase_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockUseCase_Login_Call {
	return &MockUseCase_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockUseCase_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUseCase_Login_Call) Return(_a0 string, _a1 error) *MockUseCase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, role
func (_m *MockUseCase) Register(ctx context.Context, email string, password string, role string) (*domain.User, error) {
	ret := _m.Called(ctx, email, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, error)); ok {
		return rf(ctx, email, password, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUseCase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - role string
func (_e *MockUseCase_Expecter) Register(ctx interface{}, email interface{}, password interface{}, role interface{}) *MockUseCase_Register_Call {
	return &MockUseCase_Register_Call{Call: _e.mock.On("Register", ctx, email, password, role)}
}

func (_c *MockUseCase_Register_Call) Run(run func(ctx context.Context, email string, password string, role string)) *MockUseCase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUseCase_Register_Call) Return(_a0 *domain.User, _a1 error) *MockUseCase_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Register_Call) RunAndReturn(run func(context.Context, string, string, string) (*domain.User, error)) *MockUseCase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
