// Code generated by mockery. DO NOT EDIT.

package mockschedulehandler

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreateSchedule provides a mock function with given fields: ctx, roomID, daysOfWeek, startTime, endTime
func (_m *MockUseCase) CreateSchedule(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string) (*domain.Schedule, error) {
	ret := _m.Called(ctx, roomID, daysOfWeek, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 *domain.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) (*domain.Schedule, error)); ok {
		return rf(ctx, roomID, daysOfWeek, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) *domain.Schedule); ok {
		r0 = rf(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []int, string, string) error); ok {
		r1 = rf(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type MockUseCase_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - daysOfWeek []int
//   - startTime string
//   - endTime string
func (_e *MockUseCase_Expecter) CreateSchedule(ctx interface{}, roomID interface{}, daysOfWeek interface{}, startTime interface{}, endTime interface{}) *MockUseCase_CreateSchedule_Call {
	return &MockUseCase_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, roomID, daysOfWeek, startTime, endTime)}
}

func (_c *MockUseCase_CreateSchedule_Call) Run(run func(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string)) *MockUseCase_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUseCase_CreateSchedule_Call) Return(_a0 *domain.Schedule, _a1 error) *MockUseCase_CreateSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CreateSchedule_Call) RunAndReturn(run func(context.Context, uuid.UUID, []int, string, string) (*domain.Schedule, error)) *MockUseCase_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
