// Code generated by mockery. DO NOT EDIT.

package mockusecasebooking

import (
	context "context"
	domain "github.com/ivanov-matvey/room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSlotRepository is an autogenerated mock type for the SlotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSlotRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Slot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Slot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Slot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSlotRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSlotRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSlotRepository_GetByID_Call {
	return &MockSlotRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSlotRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSlotRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSlotRepository_GetByID_Call) Return(_a0 *domain.Slot, _a1 error) *MockSlotRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Slot, error)) *MockSlotRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
