// Code generated by mockery. DO NOT EDIT.

package mockusecasebooking

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockConferenceService is an autogenerated mock type for the ConferenceService type
type MockConferenceService struct {
	mock.Mock
}

type MockConferenceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConferenceService) EXPECT() *MockConferenceService_Expecter {
	return &MockConferenceService_Expecter{mock: &_m.Mock}
}

// CreateConferenceLink provides a mock function with given fields: ctx, bookingID
func (_m *MockConferenceService) CreateConferenceLink(ctx context.Context, bookingID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CreateConferenceLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConferenceService_CreateConferenceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConferenceLink'
type MockConferenceService_CreateConferenceLink_Call struct {
	*mock.Call
}

// CreateConferenceLink is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
func (_e *MockConferenceService_Expecter) CreateConferenceLink(ctx interface{}, bookingID interface{}) *MockConferenceService_CreateConferenceLink_Call {
	return &MockConferenceService_CreateConferenceLink_Call{Call: _e.mock.On("CreateConferenceLink", ctx, bookingID)}
}

func (_c *MockConferenceService_CreateConferenceLink_Call) Run(run func(ctx context.Context, bookingID uuid.UUID)) *MockConferenceService_CreateConferenceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConferenceService_CreateConferenceLink_Call) Return(_a0 string, _a1 error) *MockConferenceService_CreateConferenceLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConferenceService_CreateConferenceLink_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *MockConferenceService_CreateConferenceLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConferenceService creates a new instance of MockConferenceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConferenceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConferenceService {
	mock := &MockConferenceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
